### ISSUE TITLE
[RMM Update]: RMM HopToDesk not available in web interface.

### ISSUE THREAD

**Issue by johnk3r** [magicsword-io/LOLRMM#25]
### RMM Tool Name

HopToDesk 

### Type of Update

General Information Update

### Update Details

I can't find HopToDesk in the web interface. I committed a few days ago in PR #12

### References

https://github.com/magicsword-io/LOLRMM/pull/12

**Comment by cyberbuff** [comment]
Hey @johnk3r, Thank you for your contribution! At the moment, we are displaying tools from the files located in [this YAML folder](https://github.com/magicsword-io/LOLRMM/tree/main/yaml) and not based on Sigma rules.

**Comment by johnk3r** [comment]
I got it.
