### ISSUE TITLE
[RMM Update]: Action1: mismatch between Security's log "Service installation event" and event ID

### ISSUE THREAD

**Issue by Koifman** [magicsword-io/LOLRMM#27]
### RMM Tool Name

Action1

### Type of Update

Forensic Artifact

### Update Details

Hi team,
In the following link:
https://lolrmm.io/tools/action1#event-log-artifacts

The first line mentions:
"Service installation event as result of Action1 installation."

However, the associated event ID is 4688, but it should be 4697.
Additionally, the service name for Action1 would be: "A1Agent":
![image](https://github.com/user-attachments/assets/3347071e-4a4f-4d44-ab7e-08ee2944e39f)

Thanks in advance,
Daniel

### References

Image attached in ticket

**Comment by nasbench** [comment]
Hey @Koifman thanks for opening this issue. I will get fixed asap
