### ISSUE TITLE
Sigma date format different than ISO 8601

### ISSUE THREAD

**Issue by wikijm** [magicsword-io/LOLRMM#32]
Hi everyone!

According to the [Sigma Rules Specification](https://github.com/SigmaHQ/sigma-specification/blob/main/specification/sigma-rules-specification.md#date), the date format in Sigma rule files must follow the ISO 8601 standard, using the separator format (YYYY-MM-DD instead of YYYY/MM/DD).

I’ve made a change in the main...wikijm:LOLRMM:patch-1 branch, but I’m not entirely sure if I modified the correct part of the code. Additionally, I’m uncertain if this change might affect other mechanisms in your GitHub repository or on the lolrmm.io website.

The reason for this change is that when I try to transform, [with that repo](https://github.com/wikijm/ConvertSigmaRepo2SentinelOnePQ),  your Sigma rules to SentinelOne Power Query using sigma-cli through GitHub Actions, I encounter the following error message: “Error occurred while processing […]_sigma.yml: Rule date ‘YYYY/MM/DD’ is invalid, must be yyyy-mm-dd”:
![image](https://github.com/user-attachments/assets/ed7bbfc2-e1b4-454d-b45b-25462dbd3952)

If this request makes sense, I can create a pull request accordingly.

Thank you for this project; I’m happy to use it for Threat Hunting! 😃

**Comment by nasbench** [comment]
Hi @wikijm 

Thanks for this issue, and yes, you can open a PR with your fix its fine.

Just FYI I already have some tuning to the sigma gen script that i'm gonna push to fix some other issues.

**Comment by wikijm** [comment]
Hi @nasbench,

Wonderful, thanks a lot!
Closing this ticket as #34 was created. 

Have a nice sunday.
