### ISSUE TITLE
Getting updates to the LOLRMM list?

### ISSUE THREAD

**Issue by axiomcs** [magicsword-io/LOLRMM#41]
(When new entries are added, as far as, getting notified)
Can you recommend how this be done somehow without having to use the API?  Perhaps an email or a webhook?  (I do see there is a json.)  And do you provide this for others?

And where did you get this list or how was it compiled?

There are so many I have not come across.

I have added the ones that are new to me to my RMM's alerting script for installed remote access tools and rmm's.

**Comment by josehelps** [comment]
@axiomcs list was compiled from various sources and our own discovery. Best way to get notify is the API or monitor the github project, no other methodology today, you could sign up for github email notifications. Glad you have found value in the list/project.
